services:
  app:
    build: .
    container_name: big-vibe-video
    restart: always
    environment:
      - VIRTUAL_HOST=bigvibetest.hopto.org
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=bigvibetest.hopto.org
      - LETSENCRYPT_EMAIL=aag99@yandex.ru
    volumes:
      - db-data:/app/apps/backend/data
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true

volumes:
  db-data:
